#!/usr/bin/env bash
set -eo pipefail

[ $# = 1 ] || {
  echo "usage: `basename $0` dir" >&2
  exit 2
}
dir=$1
job_name=ytdump/`basename "$dir"`

cd "$dir"

{
  echo "running cronjob '$job_name'"
  date
  bash -lc "
    exec alerterr \
      --name=\"\$1\" --on_err='/^ *ERROR|output file|unavailable/' -- \
      flock lock \
        bash dl.sh
  " -- "$job_name"
} 2>&1 | tee cronjob.log
