#!/usr/bin/env bash
set -eo pipefail

{
  flock -w 30 /tmp/pip_update.lock \
    pip install --user --upgrade git+https://github.com/ytdl-org/youtube-dl

  find playlists -mindepth 1 -maxdepth 1 -print0 \
    | xargs -0 -L1 -P8 -I{} ./cronjob "{}"
} 2>&1 | tee /tmp/ytdump_cronjob_all.log
