#!/usr/bin/env bash
set -eo pipefail

[ $# = 1 ] || {
  echo "usage: `basename $0` playlist_name" >&2
  exit 2
}
playlist_name=$1

cd playlists/$playlist_name
name=ytdump/$playlist_name

{
  echo "running cronjob '$name'"
  date
  bash -lc "
    exec alerterr \
      --name=$name --on_err='/^ *ERROR|output file|unavailable/' -- \
      flock lock \
        bash dl.sh
  "
} 2>&1 | tee cronjob.log
