#!/usr/bin/env bash
set -eo pipefail

[ $# -ge 2 ] || {
  echo "usage: $(basename "$0") URL RCLONE_DEST" >&2
  exit 2
}
url=$1 ; shift
dest=$1 ; shift
root=$(dirname "$0")

done=`rclone -v lsf "$dest"`
echo "$done" | ruby "$root"/dl.rb "$@" "$url"
st0=$?

rclone -v copy out "$dest" && rm -r out
st1=$?

[ $st0 = 0 -a $st1 = 0 ]
