#!/usr/bin/env bash
set -eo pipefail

[[ $# = 1 ]] || {
  echo "usage: `basename $0` [dir | arg...]" >&2
  exit 2
}
dir=$1

if [[ -d playlists/"$dir" ]]; then
  echo "docker: playlist directory: $dir" >&2
  cd playlists/"$dir"
  mkdir -p /meta/"$dir"
  ln -s /meta/"$dir" meta
  exec bash dl.sh
else
  echo "docker: command:" "$@" >&2
  exec bundle exec ruby dl.rb "$@"
fi
